steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
  dir: 'src'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_web', 'gcr.io/$PROJECT_ID/the-nimble-sloth-truck:latest']
images: ['gcr.io/$PROJECT_ID/the-nimble-sloth-truck:latest']