#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
  dir: 'src'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'the-nimble-sloth-truck:latest', 'gcr.io/$PROJECT_ID/$the-nimble-sloth-truck:$COMMIT_SHA']
images: ['gcr.io/the-nimble-sloth-truck/the-nimble-sloth-truck:$COMMIT_SHA']