environment: development
api:
  port: 80
  url: 'http://35.231.207.234/'
rabbit:
  host: localhost
  exchange: ''
  queue: tasks
  url: 'amqp://xnennbql:uu7tKh7tBcKe173L3rIYdE4921wbhPfd@bee.rmq.cloudamqp.com/xnennbql'
db:
  host: localhost
  port: 27017
  name: truck
requests:
  truck_app_id: 'truck-1234'
  token: 'L6NeUQCivmBQEsYflJeeyFkTIieJwDW2'
  warehouse_app_id: 'the-nimble-sloth-warehouse'
  router_base_url: 'https://the-nimble-sloth-router.herokuapp.com'
